Moved Manga chapters over to Decimals for fractional releases
IgnisDa/ryot pull request #1002
Opened 2024-09-03 01:07 UTC by Jacob-Tate

Modified front end to properly display fractional releases 
Modified front end to properly mark fractional releases as read 
Modified front end to properly mark all prior chapters as read

I have tested and marking completed is working.

I changed the functionality of marking all prior chapters as read since I started using the integration after the fact my lastseenchapter was 50 and I wanted to mark 1-49 but couldnt because of the implementation so it now will mark all previous chapters which may have been missed.

NOTE: I am unaware of MAL or MangaUpdates storing any fractional releases since they dont track individual chapters and the APIs return whole numbers so we will continue to receive i32/i64 values and convert them the decimal after import.

NOTE: This does not handle marking prior fractional releases as read only whole numbers since we have no way of knowing they exist.

NOTE: isNumberOrDecimalString exists to bridge the gap with the  previous schema using numbers. Due to the way the storage is occurring the previous manga entries are numbers whereas the new entries are technically strings (even though they are imported as decimal).

2024-09-03 01:47 UTC, IgnisDa requested changes
LGTM. Most superficial changes.

2024-09-03 01:47 UTC, IgnisDa commented on apps/frontend/app/routes/_dashboard.media.item.$id._index.tsx
> +		typeof value === "number" ||
use `isNumber`, `isString` from `@ryot/ts-utils`.

2024-09-03 01:47 UTC, IgnisDa commented on apps/frontend/app/routes/_dashboard.media.item.$id._index.tsx
> +			!Number.isNaN(Number.parseFloat(value)) &&
re-export `isNan` and `isFinite` from lodash from `@ryot/ts-utils` and use here.

2024-09-03 01:47 UTC, IgnisDa commented on apps/frontend/app/routes/_dashboard.media.item.$id._index.tsx
> +		if (isNumber(volume)) {
Could you remove the braces?

2024-09-03 06:04 UTC, IgnisDa approved these changes
LGTM. Will merge later today. Thanks for the contribution!

2024-09-03 16:09 UTC, IgnisDa requested changes
Please run `moon r frontend:lint` and address the lint errors.

Edit: Looks like biome does not like usage of `isNan` and `isFinite` from lodash. In that case, please revert those changes. Keep the `isNumber` and `isString`. Sorry for the back and forth 😝.

2024-09-03 17:45 UTC, Jacob-Tate commented
Should be good now. Let me know if anymore changes are needed.

2024-09-04 05:23 UTC, IgnisDa commented
`moon r frontend:typecheck` gives a lot of errors.

2024-09-04 07:11 UTC, Jacob-Tate commented
Resolved that

2024-09-04 07:14 UTC, IgnisDa commented on libs/ts-utils/src/index.ts
> +import isInteger from "lodash/isInteger";
is biome fine with this?

2024-09-04 16:19 UTC, IgnisDa approved these changes

2024-09-04 16:19 UTC, merged